labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **NOTE**: Please ensure that you're not creating a duplicate report by searching the [issues](https://github.com/orcasecurity/kte/issues)/[discussions](https://github.com/orcasecurity/kte/discussions) before you continue.
  - type: textarea
    attributes:
      label: Description
      description: Briefly describe the problem you are having in a few paragraphs.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Desired Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: What happened instead?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction Steps
      description: How do you trigger this bug? Please walk us through it step by step.
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        We would be happy if you could share how you are using KTE [here](https://github.com/orcasecurity/kte/discussions/new?category=adopters).